### PR TITLE
Add KeyedChain GufeTokenizable representation

### PR DESCRIPTION
**Pull request by ianmkenney**
This PR implements the `KeyedChain` representation for `GufeTokenizable`s originally implemented in 
[alchemiscale](https://github.com/openforcefield/alchemiscale). As it appears general and useful enough, an upstream implementation seems appropriate.

The `KeyedChain` representation encodes a `GufeTokenizable` as a list of Tuples with the `GufeKey` and keyed dicts of other required tokenizables as their first and second elements, respectively. These tokenizables are sorted such that, when decoded in order, all required dependencies have been satisfied while accounting for duplicated dependencies down the tree structure. This representation is particularly useful when encoding/decoding `GufeTokenizables` on systems without a populated `TOKENIZATION_REGISTRY`.

- [x] Documentation
- [x] Tests

### CODE REVIEW

**Comment by ianmkenney** [comment]
@richardjgowers I think this is ready.

**Comment by dotsdl** [comment]
I'll take on review @ianmkenney!

**Comment by IAlibay** [comment]
Thanks for taking on the review @dotsdl - maybe this is a good start for a more regular GUFE meeting?

**Comment by dotsdl** [comment]
@ianmkenney is this ready for review in your view?

**Comment by ianmkenney** [comment]
@dotsdl should be good for review

**Review by dotsdl — APPROVED** [review]
Looks great @ianmkenney! Thank you for this contribution!

Merging!

**Pull request merged**
