### PR TITLE
ignore another big auto format

### PR DESCRIPTION
**Pull request by mikemhenry**
Tips
* Comment "pre-commit.ci autofix" to have pre-commit.ci atomically format your PR.
  Since this will create a commit, it is best to make this comment when you are finished with your work.

Checklist
* [ ] Added a ``news`` entry

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Okay this also tests that the PR template is now working! We can access the release template with a quary URL param, I don't know where we want to put a link to that, maybe on our docs or wiki? This can be future work.

**Comment by mikemhenry** [comment]
Also I turned on "only squash commits" via the web UI since we talked about doing that but it never happened. 

@ianmkenney can you check to see if when you run pre-commit locally now it doesn't try and change anything?

**Review by atravitz — APPROVED** [review]

**Comment by ianmkenney** [comment]
```shell
    cd `mktemp -d`
    git clone https://github.com/openfreeenergy/gufe && cd gufe
    micromamba create -p ../env/ python=3.11 pre-commit --yes
    micromamba -p ../env/ run pre-commit run --all-files
```

shows that no files were reformatted. Do we know why it took multiple calls of the bot to fix things? That sounds like a bug.

**Comment by mikemhenry** [comment]
> Do we know why it took multiple calls of the bot to fix things? That sounds like a bug.

I looked into it and looking at the logs (below) it had to do with an interaction where pyupgrade made a change ([converted a `.format` into a `f-string`](https://github.com/OpenFreeEnergy/gufe/pull/431/commits/8074122efe93c81dd4d1fa331433532e98849a38)) that black didn't like ([different line wrapping style](https://github.com/OpenFreeEnergy/gufe/pull/431/commits/3a4cfa3d53019d5e6950c3134761327a2d7230bf)), so black had to run again on those changes. For the last run nothing changed.

I will check to see if pyupgrade has any config options to play nicer with black. 


image
image
image

**Comment by dotsdl** [comment]
@mikemhenry in discussion with @ianmkenney, can we just drop `pyupgrade` if it's fighting with black? We want to completely avoid nondeterminism in this system.

**Comment by dotsdl** [comment]
@mikemhenry works for me! We also have agreement from @atravitz, @jthorton, and @ianmkenney!

**Comment by mikemhenry** [comment]
Okay this should be good to go now!

**Comment by ianmkenney** [comment]
lgtm, thanks @mikemhenry!

**Review by ianmkenney — APPROVED** [review]

**Review by jthorton — APPROVED** [review]
LGTM!

**Pull request merged**
