### PR TITLE
Fixing the conda cron

### PR DESCRIPTION
**Pull request by IAlibay**
This should fix any issues we've had lately.

### CODE REVIEW

**Comment by IAlibay** [comment]
Now it's failing properly.

**Comment by mikemhenry** [comment]
```
2024-11-12T13:16:04.6116660Z >       assert in_lines == out_lines
2024-11-12T13:16:04.6117140Z E       AssertionError: assert ['HETATM    1...  H  \n', ...] == ['HETATM    1...  H  \n', ...]
2024-11-12T13:16:04.6117550Z E         
2024-11-12T13:16:04.6118210Z E         At index 14 diff: 'ATOM     15  OE2 GLU A   2      68.596  19.156  21.677  1.00  0.00           O1-\n' != 'ATOM     15  OE2 GLU A   2      68.596  19.156  21.677  1.00  0.00           O  \n'
2024-11-12T13:16:04.6118850Z E         
2024-11-12T13:16:04.6119020Z E         Full diff:
2024-11-12T13:16:04.6119210Z E           [
2024-11-12T13:16:04.6119530Z E               'HETATM    1  CH3 ACE A   1      69.744  11.567  19.362  1.00  '
2024-11-12T13:16:04.6119910Z E               '0.00           C  \n',
2024-11-12T13:16:04.6120290Z E               'HETATM    2  C   ACE A   1      69.053  12.763  20.004  1.00  '
2024-11-12T13:16:04.6120650Z E               '0.00           C  \n',
2024-11-12T13:16:04.6121030Z E               'HETATM    3  O   ACE A   1      67.851  12.703  20.259  1.00  '
2024-11-12T13:16:04.6121390Z E               '0.00           O  \n',
2024-11-12T13:16:04.6121770Z E               'HETATM    4  H1  ACE A   1      69.181  11.231  18.492  1.00  '
2024-11-12T13:16:04.6122140Z E               '0.00           H  \n',
2024-11-12T13:16:04.6122510Z E               'HETATM    5  H2  ACE A   1      70.755  11.816  19.037  1.00  '
2024-11-12T13:16:04.6123110Z E               '0.00           H  \n',
2024-11-12T13:16:04.6123490Z E               'HETATM    6  H3  ACE A   1      69.806  10.743  20.072  1.00  '
2024-11-12T13:16:04.6123850Z E               '0.00           H  \n',
2024-11-12T13:16:04.6124220Z E               'ATOM      7  N   GLU A   2      69.807  13.849  20.242  1.00  '
2024-11-12T13:16:04.6124580Z E               '0.00           N  \n',
2024-11-12T13:16:04.6125080Z E               'ATOM      8  CA  GLU A   2      69.255  15.135  20.671  1.00  '
2024-11-12T13:16:04.6125460Z E               '0.00           C  \n',
2024-11-12T13:16:04.6125820Z E               'ATOM      9  C   GLU A   2      68.759  15.888  19.424  1.00  '
2024-11-12T13:16:04.6126180Z E               '0.00           C  \n',
2024-11-12T13:16:04.6126560Z E               'ATOM     10  O   GLU A   2      69.474  15.958  18.424  1.00  '
2024-11-12T13:16:04.6126920Z E               '0.00           O  \n',
2024-11-12T13:16:04.6127280Z E               'ATOM     11  CB  GLU A   2      70.305  15.908  21.501  1.00  '
2024-11-12T13:16:04.6127650Z E               '0.00           C  \n',
2024-11-12T13:16:04.6128020Z E               'ATOM     12  CG  GLU A   2      69.757  17.154  22.248  1.00  '
2024-11-12T13:16:04.6128390Z E               '0.00           C  \n',
2024-11-12T13:16:04.6128760Z E               'ATOM     13  CD  GLU A   2      69.581  18.433  21.417  1.00  '
2024-11-12T13:16:04.6129130Z E               '0.00           C  \n',
2024-11-12T13:16:04.6129490Z E               'ATOM     14  OE1 GLU A   2      70.425  18.679  20.530  1.00  '
2024-11-12T13:16:04.6129860Z E               '0.00           O  \n',
2024-11-12T13:16:04.6130220Z E               'ATOM     15  OE2 GLU A   2      68.596  19.156  21.677  1.00  '
2024-11-12T13:16:04.6130590Z E         -     '0.00           O  \n',
2024-11-12T13:16:04.6130840Z E         ?                      ^^
2024-11-12T13:16:04.6131110Z E         +     '0.00           O1-\n',
2024-11-12T13:16:04.6131360Z E         ?                      ^^
2024-11-12T13:16:04.6131720Z E               'ATOM     16  H   GLU A   2      70.789  13.841  20.010  1.00  '
```

Probably some dep changed something upstream, since things are going from N1 to N for example.

**Comment by atravitz** [comment]
I was not able to reproduce this error locally on my M1 macbook (macos 14.6.1)

**Comment by mikemhenry** [comment]
my hunch is still some upstream package changed since we run these pdb round trips on PRs

**Comment by atravitz** [comment]
> my hunch is still some upstream package changed since we run these pdb round trips on PRs

Yep, it's openmm 8.2.0. I was able to reproduce the error using mike's env, and then resolve the error by just downgrading openmm to 8.1.2.

**Comment by mikemhenry** [comment]
Ah openmm isn't a direct gufe dependency, but openff-toolkit is, which pulls in openff-interchange

**Comment by mikemhenry** [comment]
Actually it is a direct dependency, but we don't list it in our recipe, and have just gotten lucky it gets pulled in, see:
https://github.com/conda-forge/gufe-feedstock/blob/main/recipe/meta.yaml
and
https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/components/proteincomponent.py#L12

**Comment by mikemhenry** [comment]
I bet it is this PR 
https://github.com/openmm/openmm/pull/4630

**Comment by mikemhenry** [comment]
Looking at that PR, I think we just need to update our tests since the new behavior is correct.

This PR: https://github.com/OpenFreeEnergy/gufe/pull/406 confirms that it is with 8.2.

I think we just need to update the test "reference" PDB to be the new "correct" one

**Comment by IAlibay** [comment]
Thanks for looking into this @mikemhenry - I agree, the formal charges make a lot of sense / adhere better to reality.

My propose plan is:

1. For now we pin gufe to openmm < 8.2 on conda-forge
2. We merge this PR
3. We pin openmm < 8.2 in the environment.yaml file here too so that we don't halt other PRs
4. We follow up with another issue/PR to fix things for openmm 8.2

Do you both agree @atravitz and @mikemhenry ?

**Comment by atravitz** [comment]
related: https://github.com/conda-forge/gufe-feedstock/pull/40

**Pull request merged**
