### PR TITLE
remove python 3.8 CI

### PR DESCRIPTION
**Pull request by richardjgowers**

### CODE REVIEW

**Comment by IAlibay** [comment]
Do we want to bump to 3.10 or do we have a dependency block here?

**Comment by richardjgowers** [comment]
let's find out I guess

**Comment by richardjgowers** [comment]
Encountered problems while solving:
    - package rdkit-Release_2017_09-py36_0 requires python 3.6*, but none of the providers can be installed

**Comment by mikemhenry** [comment]
I'd vote we add python 3.10 but not require it for merging and we can use that as a canary. 

`rdkit-Release_2017_09` Are we pinning that somewhere?

**Comment by mikemhenry** [comment]
@richardjgowers I think this is ready to go!

**Pull request merged**
