### PR TITLE
A hill I'm ready to die upon [nomenclature changes]

### PR DESCRIPTION
**Pull request by IAlibay**
Last I heard it was  OpenFF not OpenF 🙃

### CODE REVIEW

**Comment by IAlibay** [comment]
🤦🏽 this goes upstream doesn't it

**Comment by mikemhenry** [comment]
Is this a joke?

**Review by dwhswenson — APPROVED** [review]
I don't want @IAlibay to die on a hill!

I mean, I don't particularly want @IAlibay to die at all, but definitely not on a hill.

(Also, yes, this should be correct for consistency.)

**Review by mikemhenry — APPROVED** [review]

**Comment by mikemhenry** [comment]
Depending on how you install gufe @ijpulidos you will need to update once this is merged in.

**Comment by IAlibay** [comment]
It _shouldn't_ affect downstream unless you directly access the base class?

**Comment by richardjgowers** [comment]
Normally a class name change would cause some hashes to change, but since this is a base class this won't break anything.

**Comment by richardjgowers** [comment]
@IAlibay if you really want this hill, shouldn't we use `force_field_settings` not `forcefield_settings`?

**Comment by IAlibay** [comment]
technically yeah, but that'll actually make downstream worse imho

**Pull request merged**
